apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "estadea.fullname" . }}-manager-role
  labels:
    {{- include "estadea.labels" . | nindent 4 }}
rules:
  - apiGroups: ["reaper.estadea.io"]
    resources: ["podreapers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["reaper.estadea.io"]
    resources: ["podreapers/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["reaper.estadea.io"]
    resources: ["podreapers/finalizers"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
