name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'operator/helm/estadea/**'
      - 'docs/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: operator/helm
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish docs and metadata to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          cp $GITHUB_WORKSPACE/docs/index.html .
          cp $GITHUB_WORKSPACE/operator/helm/artifacthub-repo.yml .
          git add index.html artifacthub-repo.yml
          git diff --cached --quiet || git commit -m "chore: update docs and artifacthub metadata"
          git push origin gh-pages
